import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {AuthProvider} from "@/context/AuthContext";
import AdminSidebar from "@/components/AdminSidebar";

export const metadata: Metadata = {
    title: "Cortex UI",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="de">
            <body className={`antialiased`}>
                <AuthProvider>
                    <div className={"min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-50 flex"}>
                        <AdminSidebar />
                        <main className={"flex-1 overflow-auto"}>
                            {children}
                        </main>
                    </div>
                </AuthProvider>
            </body>
        </html>
    );
}
